import { existsSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

import fr from '../i18n/fr.json'
import { locales } from '../i18n'
import { isNarrated, narrationUrl } from './narrationAudio'

const AUDIO_ROOT = join(process.cwd(), 'public', 'audio')
const narratedKeys = (Object.keys(fr) as (keyof typeof fr)[]).filter((key) => isNarrated(key))

describe('narrationUrl', () => {
  it('maps a key to the path the generator writes', () => {
    expect(narrationUrl('fr', 'chapter.wow.say.open')).toContain('audio/fr/chapter-wow-say-open.mp3')
    expect(narrationUrl('en', 'chapter.wow.say.open')).toContain('audio/en/chapter-wow-say-open.mp3')
  })
})

/*
 * The clips are generated by a Python script and committed. Nothing at build
 * time notices when the two drift apart — a new narrated line simply plays
 * silence, in front of a child who cannot read the sentence yet. These tests
 * are the join.
 */
describe('every narrated line has a clip', () => {
  it('has lines to check at all', () => {
    expect(narratedKeys.length).toBeGreaterThan(15)
  })

  for (const locale of locales) {
    it(`is complete for ${locale}`, () => {
      const missing = narratedKeys.filter(
        (key) => !existsSync(join(AUDIO_ROOT, locale, `${key.replaceAll('.', '-')}.mp3`)),
      )
      expect(missing).toEqual([])
    })

    it(`has no clip left behind by a renamed key in ${locale}`, () => {
      const expected = new Set(narratedKeys.map((key) => `${key.replaceAll('.', '-')}.mp3`))
      const orphans = readdirSync(join(AUDIO_ROOT, locale)).filter((file) => !expected.has(file))
      expect(orphans).toEqual([])
    })

    it(`holds real audio, not empty files, in ${locale}`, () => {
      const suspicious = narratedKeys.filter((key) => {
        const path = join(AUDIO_ROOT, locale, `${key.replaceAll('.', '-')}.mp3`)
        // A second of speech at 64 kbps is about 8 KB; anything under 4 KB is a
        // truncated encode rather than a short sentence.
        return !existsSync(path) || statSync(path).size < 4096
      })
      expect(suspicious).toEqual([])
    })
  }
})
